implement Order
Roma1990Melnichuk/book pull request #11
Opened 2024-11-19 19:44 UTC by Roma1990Melnichuk

2024-11-20 13:22 UTC, Elena-Bruyako requested changes
see comments

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/dto/UpdateOrderStatusRequest.java
> +public class UpdateOrderStatusRequest {
Do we need validate request?

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/dto/OrderRequest.java
> +public class OrderRequest {
Do we need validate request?

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Order.java
> +    @ManyToOne()
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Order.java
> +    @Column(name = "shipping_address", nullable = false)
```suggestion
    @Column(nullable = false)
    private LocalDateTime orderDate;

    @Column(nullable = false)
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/OrderItem.java
> +    @ManyToOne()
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/OrderItem.java
> +    @ManyToOne()
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/OrderItem.java
> +    @Column(name = "is_deleted",nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/mapper/OrderMapper.java
> +@Mapper(componentModel = "spring")
```suggestion
@Mapper(componentModel = "spring", uses = OrderItemMapper.class)
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/OrderServiceImpl.java
> +    public OrderDto orderReturn(OrderRequest request, User user) {
```suggestion
    public OrderDto createOrder(OrderRequest request, User user) {
```

2024-11-20 13:22 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/OrderServiceImpl.java
> +            OrderItem orderItem = new OrderItem();
let's divide logic
could you use separate methods?

2024-11-21 08:06 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few comments!

2024-11-21 08:06 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/controller/OrderController.java
> +    @ResponseStatus(HttpStatus.OK)
It’s  default response status

2024-11-21 08:06 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/dto/OrderDto.java
> +
```suggestion
```
Only one empty line at the end of the file

2024-11-21 08:06 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/dto/OrderRequest.java
> +    @NotEmpty(message = "Shipping address is required")
With literals better use NotBlank

2024-11-21 08:06 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/dto/UpdateOrderStatusRequest.java
> +    @NotNull(message = "Status is required")
the same 
or better use 
```
private Status status;
```

2024-11-21 08:06 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/entity/OrderItem.java
> +@SQLDelete(sql = "Update orderItems SET is_deleted = TRUE WHERE id = ?")
```suggestion
@SQLDelete(sql = "UPDATE order_items SET is_deleted = TRUE WHERE id = ?")
```

2024-11-21 08:06 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/service/OrderServiceImpl.java
> +        order.setStatus(Order.Status.valueOf(status.name()));
```suggestion
        order.setStatus(status);
```
Why do you complicate it?

2024-11-22 10:29 UTC, Elena-Bruyako requested changes
almost perfect

2024-11-22 10:29 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Order.java
> +    @Column(name = "is_deleted",nullable = false)
```suggestion
    @Column(name = "is_deleted", nullable = false)
```

2024-11-22 10:29 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/OrderServiceImpl.java
> +        Order order = orderRepository.findById(orderId)
you could find orderItem by `findByIdAndOrderId`

2024-11-22 10:29 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/OrderServiceImpl.java
> +        order.setStatus(Order.Status.PENDING);
minor comment
you can initialise PENDING status and `LocalDateTime.now()` in Order entity

2024-11-23 11:36 UTC, Elena-Bruyako requested changes
add valid annotation to controller

2024-11-23 11:36 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/OrderController.java
> +    public OrderDto placeOrder(@RequestBody OrderRequest request, Authentication authentication) {
```suggestion
    public OrderDto placeOrder(@RequestBody @Valid OrderRequest request, Authentication authentication) {
```

2024-11-23 11:36 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/OrderController.java
> +                                      @RequestBody UpdateOrderStatusRequest request) {
```suggestion
                                      @RequestBody @Valid UpdateOrderStatusRequest request) {
```

2024-11-24 11:28 UTC, Elena-Bruyako approved these changes

2024-11-24 12:23 UTC, merged