implement GlobalExceptionHandler
Roma1990Melnichuk/book pull request #4
Opened 2024-10-25 18:53 UTC by Roma1990Melnichuk

2024-10-25 19:21 UTC, sarakhmen requested changes
I don't see relevant changes in terms of this PR

2024-10-26 02:48 UTC, Roma1990Melnichuk commented
I pust it to main - request to either look at the commit 
https://github.com/Roma1990Melnichuk/book/pull/4/commits/d11bcbc84534f4fbfcb90d8c82a734feaf87696f#diff-256a0c62344e7f4689917a1cf6a79137855ff69b43e96a08b5683c7c685f1bc3 
- or please tell me how to fix it

2024-10-26 11:06 UTC, Roma1990Melnichuk commented
rolled back to _d11bcbc_ but it seems something went wrong (didn't find the creation of the CustomGlobalExceptionHandler class)

2024-10-26 16:04 UTC, sarakhmen approved these changes

2024-10-26 17:41 UTC, merged