implement User,secure logic
Roma1990Melnichuk/book pull request #6
Opened 2024-10-29 06:03 UTC by Roma1990Melnichuk

2024-10-29 11:03 UTC, JJJazl requested changes

2024-10-29 11:03 UTC, JJJazl commented on src/main/java/com/bookstore/controller/AuthController.java
> +    public UserResponseDto registerUser(@Valid @RequestBody UserRegistrationRequestDto requestDto)
Please, add the appropriate status code for POST method

2024-10-29 11:03 UTC, JJJazl commented on src/main/java/com/bookstore/exception/RegistrationException.java
> +public class RegistrationException extends Exception {
```suggestion
public class RegistrationException extends RuntimeException {
```

2024-10-29 11:03 UTC, JJJazl commented on src/main/java/com/bookstore/service/UserService.java
> +            throws RegistrationException;
```suggestion
    UserResponseDto register(UserRegistrationRequestDto requestDto);
```

2024-10-29 11:03 UTC, JJJazl commented on src/main/java/com/bookstore/controller/AuthController.java
> +            throws RegistrationException {
```suggestion
    public UserResponseDto registerUser(@Valid @RequestBody UserRegistrationRequestDto requestDto) {
```

2024-10-29 11:03 UTC, JJJazl commented on src/main/java/com/bookstore/service/UserServiceImpl.java
> +    public UserResponseDto register(UserRegistrationRequestDto requestDto)
```suggestion
    @Override
    @Transactional
    public UserResponseDto register(UserRegistrationRequestDto requestDto)
```

2024-10-29 11:03 UTC, JJJazl commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
Let's have an explicit constraint name for PK (primary key)

2024-10-30 09:18 UTC, okuzan requested changes

2024-10-30 09:18 UTC, okuzan commented on src/main/java/com/bookstore/service/UserServiceImpl.java
> +            throws RegistrationException {
not fixed, it should be unchecked exception

2024-10-30 09:18 UTC, okuzan commented on src/main/java/com/bookstore/controller/AuthController.java
> +
```suggestion
```

2024-10-30 12:52 UTC, Elena-Bruyako requested changes
see comments

2024-10-30 12:52 UTC, Elena-Bruyako commented on pom.xml
> +		<commons-beanutils.version>1.9.4 </commons-beanutils.version>
remove this dependency

2024-10-30 12:52 UTC, Elena-Bruyako commented on pom.xml
> +			<version>${spring-boot-starter-security.version}</version>
read about starters

```suggestion
```

2024-10-30 12:52 UTC, Elena-Bruyako commented on pom.xml
> +			<version>${spring-boot-starter-web.version}</version>
don't need to specify the version, spring-boot-parent already provides it

```suggestion
```

2024-10-30 12:52 UTC, Elena-Bruyako commented on pom.xml
> +			<artifactId>spring-security-core</artifactId>
remove dependency

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/AuthController.java
> +    @PostMapping("/registration")
add Swagger annotations to controller

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/User.java
> +    @Column(name = "shipping_address")
Don't need to add `name` attribute to Column annotation. Hibernate automatically creates column name in snake_case format

```suggestion
    @Column(nullable = false)
    private String firstName;
    @Column(nullable = false)
    private String lastName;
```

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(requestDto.getEmail())) {
```

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/UserServiceImpl.java
> +        return userMapper.toUserResponseDto(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toUserResponseDto(user);
```

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/dto/UserRegistrationRequestDto.java
> +        patternOf = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)[A-Za-z\\d]{8,}$")
replace this pattern as a constant to validator

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/validation/FieldMatchValidator.java
> +            return (firstFieldValue == null && secondFieldValue == null)
you can use Objects.equals()

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto= update
revert
```suggestion
spring.jpa.hibernate.ddl-auto=validate
```

2024-10-30 12:52 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: is_deleted
didn't find isDeleted column in User entity

2024-10-31 12:55 UTC, Elena-Bruyako requested changes
see comments

2024-10-31 12:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/AuthController.java
> +
remove empty line

2024-10-31 12:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/AuthController.java
> +
same here

2024-10-31 12:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/User.java
> +    @Column(name = "shipping_address")
```suggestion
```

2024-10-31 12:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/validation/FieldMatchValidator.java
> +    private String pattern;
```suggestion
    public static final String PASSWORD_PATTERN =
            "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)[A-Za-z\\d]{8,}$";
```

2024-10-31 12:55 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/validation/PasswordValidator.java
> +public class PasswordValidator {
remove

2024-11-01 09:27 UTC, ahoienko approved these changes
Good job!

2024-11-01 12:50 UTC, merged