implement categories
Roma1990Melnichuk/book pull request #9
Opened 2024-11-10 05:35 UTC by Roma1990Melnichuk

2024-11-11 14:06 UTC, Elena-Bruyako requested changes
see comments

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/config/MapperConfig.java
> +public class MapperConfig {
Haven't implemented Mapper before?

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/CategoryController.java
> +@RequestMapping("/api/categories")
You can add `server.servlet.context-path=/api` to app properties

```suggestion
@RequestMapping("/categories")
```

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/controller/CategoryController.java
> +    public SuccessResponse<List<CategoryDto>> getAll(Pageable pageable) {
It's better to return Page instead of List

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Book.java
> -@Where(clause = "is_deleted = false")
Why did you remove it?

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Book.java
> +    public Book() {
use Lombok annotation instead of generating default constructor

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Book.java
> +    private Set<Category> categories;
```suggestion
    private Set<Category> categories = new HashSet<>();
```

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/entity/Category.java
> +    private boolean isDeleted = false;
```suggestion
    @Column(nullable = false)
    private boolean isDeleted = false;
```

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/CategoryServiceImpl.java
> +        Category categoryFromDB = getModelById(id);
```suggestion
        Category category = getModelById(id);
```

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/CategoryServiceImpl.java
> +        category.setId(id);
```suggestion
        categoryMapper.updateCategoryFromDto(categoryDto, category);
```

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/service/CategoryServiceImpl.java
> +                && categoryRepository.existsByName(newName)) {
a little bit confusing with this checking, if the category already exists by name you throw an exception. What for?

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/resources/data/books-categories.csv
> +book_id	category_id
why do you need this csv?

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/07-loaddata-categories.yml 
> +      id: loaddata-categories
Looks like redundant changeset

2024-11-11 14:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/09-loaddata-books-categories.yml 
> +      id: loaddata-books-categories
same here

2024-11-12 08:47 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix a few comments ;)

2024-11-12 08:47 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/mapper/CategoryMapper.java
> +
```suggestion
```

2024-11-12 08:47 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/exception/EntityAlreadyExistsException.java
> +public class EntityAlreadyExistsException extends RuntimeException {
Should you handle this exception?  Let’s use response status conflict.

2024-11-12 08:47 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/controller/CategoryController.java
> +    public SuccessResponse<List<BookDtoWithoutCategoryIds>> getBooksByCategoryId(
better return page here

2024-11-12 08:47 UTC, liliia-ponomarenko commented on src/main/java/com/bookstore/controller/CategoryController.java
> +    @ResponseStatus(HttpStatus.CREATED)
Looks like redundant  annotation

2024-11-13 10:03 UTC, ahoienko requested changes
Very nice, left minor comment

2024-11-13 10:03 UTC, ahoienko commented on src/main/java/com/bookstore/controller/CategoryController.java
> +    public SuccessResponse<Page<BookDtoWithoutCategoryIds>> getBooksByCategoryId(
```suggestion
    public Page<BookDtoWithoutCategoryIds> getBooksByCategoryId(
```

2024-11-13 13:20 UTC, okuzan approved these changes

2024-11-13 13:20 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yml
it's totally okay to use .yaml, even more preferable. Windows used to have file extensions of three letters, now it's no longer strict

2024-11-13 13:20 UTC, okuzan commented on src/main/resources/db/changelog/changes/05-insert-users.yml
> +                  value: "$2a$10$toArBF/64iNeCxoiHme8G.XjSoa9TFGRX1aNel5jSRxR0Yav915ga"
add #123456 comment to this password hash, otherwise it's of no use to anybody

2024-11-13 15:08 UTC, merged